/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;
import Clases.ManagerSolicitud;
import Clases.ManagerComplemento;
import Clases.ManagerInventario;
import Clases.ManagerPermisos;
import Clases.ManejadorInventario;
import static Interfaces.Principal.Username;
import static Interfaces.Principal.tabbedPrincipal;
import static Interfaces.Principal.tablaSolicitudes;
import static Interfaces.tablaDetalleInventario.tablaCoincidencias;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author kevin
 */
public class ventana_AtenderSolicitud extends javax.swing.JDialog {
    ManagerSolicitud manager_solicitud;
    ManagerComplemento manager_complemento;
    ManagerPermisos manager_permisos;
    ManagerInventario manager_inventario;
    ManejadorInventario manejador_inventario;
    String id_Producto;
    
    /**
     * Creates new form ventana_AtenderSolicitud
     */
    public ventana_AtenderSolicitud(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        manager_solicitud = new ManagerSolicitud();
        manager_complemento = new ManagerComplemento();
        manager_permisos = new ManagerPermisos();
        manager_inventario = new ManagerInventario();
        manejador_inventario = new ManejadorInventario();
        
        campoRuta.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnImagen = new javax.swing.JButton();
        imagenProducto = new javax.swing.JLabel();
        campoRuta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btnCancelar.setText("  Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(300, 400, 121, 33);

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btnAceptar.setText("  Aceptar");
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(180, 400, 115, 33);

        jPanel2.setLayout(null);

        btnImagen.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btnImagen.setText("...");
        btnImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });
        jPanel2.add(btnImagen);
        btnImagen.setBounds(540, 330, 30, 20);
        jPanel2.add(imagenProducto);
        imagenProducto.setBounds(0, 0, 580, 360);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 580, 360);
        jPanel1.add(campoRuta);
        campoRuta.setBounds(460, 400, 150, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formularios.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-20, -20, 670, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        boolean estado = false;
        if(Principal.estadoSolicitud.equals("SOLICITUD PERSONAL")){
            estado = manejador_inventario.actualizar_Solicitud(Principal.idPendiente, Principal.empleadoSolicitud);
        }else{
            estado = manager_solicitud.actualizar_Solicitud(Principal.idPendiente, Principal.estadoPendiente);
        }
        
        if(estado){
            if(manager_solicitud.guardarImagenSolicitud(id_Producto, campoRuta.getText())){
                
            }
            JOptionPane.showMessageDialog(null, "La solicitud "+Principal.idPendiente+" se atendio, paso de solicitud a pendiente "+Principal.estadoPendiente+".");
            tablaSolicitudes.setModel(manager_solicitud.tabla_Solicitudes(manager_permisos.verTablaSolicitudes(Username)));
                int solicitud = manager_complemento.cantidadSolicitudes(manager_permisos.verTablaSolicitudes(Username));
                if(solicitud > 0){
                    tabbedPrincipal.setTitleAt(3, "Solicitudes ("+solicitud+")");//Le damos el nombre a esa pestaña
                }//if cantidad
                else{
                    tabbedPrincipal.setTitleAt(3, "Solicitudes");//Le damos el nombre a esa pestaña
                }
            this.dispose();
            
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();

        //        fc.setFileFilter(new FileNameExtensionFilter(".PNG", ".png"));
        //        fc.setFileFilter(new FileNameExtensionFilter(".JPG", "Archivos de imagen"));
        //        fc.setFileFilter(new FileNameExtensionFilter(".BMP", "Archivos de imagen"));
        //        fc.setFileFilter(new FileNameExtensionFilter(".JPEG", "Archivos de imagen"));
        int respuesta = fc.showOpenDialog(this);
        //Comprobar si se ha pulsado Aceptar
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            //Mostrar el nombre del archvivo en un campo de texto
            campoRuta.setText(fc.getSelectedFile().toString());

        }//if
        String path = campoRuta.getText();
        URL url = this.getClass().getResource(path);
        System.err.println("" + path);
        ImageIcon imagen = new ImageIcon(path);
        ImageIcon icono = new ImageIcon(imagen.getImage().getScaledInstance(imagenProducto.getWidth(), imagenProducto.getHeight(), Image.SCALE_DEFAULT));
        imagenProducto.setIcon(icono);
        //        ImageIcon image = new ImageIcon(i);
        //        imagenVehiculo.setIcon(image);
        //        this.repaint();
    }//GEN-LAST:event_btnImagenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        id_Producto = manager_solicitud.getProductoSolicitud(Principal.idPendiente);
        
        
        try {
            metodoImagen();
        } catch (IOException ex) {
            Logger.getLogger(ventana_AtenderSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ventana_AtenderSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_formWindowOpened
    
    public void metodoImagen() throws IOException, SQLException {
        cargarImagen(id_Producto);
    }
    
    public void cargarImagen(String producto) throws IOException, SQLException {

        Image i = null;
        i = javax.imageio.ImageIO.read(manager_inventario.leerImagen(producto).getBinaryStream());
//        ImageIcon image = new ImageIcon(i);
//        imagenVehiculo.setIcon(image);
//        this.repaint();
        try {
            ImageIcon fot = new ImageIcon(i);
            ImageIcon icono = new ImageIcon(fot.getImage().getScaledInstance(imagenProducto.getWidth(), imagenProducto.getHeight(), Image.SCALE_DEFAULT));
            imagenProducto.setIcon(icono);
            this.repaint();
        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener la imagen del producto!", "Información!", JOptionPane.WARNING_MESSAGE);

        }//catch

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_AtenderSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_AtenderSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_AtenderSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_AtenderSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventana_AtenderSolicitud dialog = new ventana_AtenderSolicitud(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JTextField campoRuta;
    private javax.swing.JLabel imagenProducto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
