/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Conexion;
import Clases.PreConexion;

import com.alee.laf.WebLookAndFeel;
import com.sun.glass.events.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author oscar
 */
public class ventanaServer extends javax.swing.JFrame {
    PreConexion preconexion;
    
    Conexion con;
    public static boolean estado = true; 
    
    
    /**
     * Creates new form ventanaServer
     */
    public ventanaServer() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        campoPass.setHorizontalAlignment(campoPass.CENTER);
        
       
        preconexion = new PreConexion();
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/IEE.png")).getImage());
        con = new Conexion();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        avisoLabel = new javax.swing.JLabel();
        campoPass = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acceso al servidor");
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setLayout(null);

        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton2.setText(" Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(240, 140, 120, 30);

        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton3.setText(" Continuar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(80, 140, 130, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setText("Introduzca la contraseña de acceso.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 10, 340, 40);

        avisoLabel.setForeground(new java.awt.Color(153, 153, 153));
        avisoLabel.setText("Advertencia: Esta configuración debe ser realizada por un administrador.");
        jPanel2.add(avisoLabel);
        avisoLabel.setBounds(30, 110, 430, 14);

        campoPass.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        campoPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPassKeyReleased(evt);
            }
        });
        jPanel2.add(campoPass);
        campoPass.setBounds(60, 70, 310, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formularios.png"))); // NOI18N
        fondo.setText("jLabel1");
        jPanel2.add(fondo);
        fondo.setBounds(0, 0, 460, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PrimerInicio primerinicio = new PrimerInicio();
        primerinicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if(!campoPass.getText().equals("")){
            metodoIngresar();
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese la contraseña del servidor","Información",JOptionPane.INFORMATION_MESSAGE);
        }
    

    }//GEN-LAST:event_jButton3ActionPerformed

    private void campoPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPassKeyReleased
         // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (!campoPass.getText().equals("")) {
                metodoIngresar();
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese la contraseña del servidor", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_campoPassKeyReleased
    
    public void metodoIngresar(){
        //DEBE EXISTIR EL CAMPO PASSWORD LLENO EN LA BASE DE DATOS
        if (preconexion.getPass().equals(campoPass.getText())) {
            System.err.println("ACCESO CORRECTO");
            try {
                preconexion.actualizarPrimeraConexion("localhost", InetAddress.getLocalHost().getHostAddress(), campoPass.getText(), "ACTIVO");
                JOptionPane.showMessageDialog(null, "Se ha realizado con exito el registro unico del servidor!!!", "Información", JOptionPane.INFORMATION_MESSAGE);
                guardarIP();
                Login login = new Login();
                login.setVisible(true);

                this.dispose();
            } catch (UnknownHostException ex) {
                Logger.getLogger(ventanaServer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ventanaServer.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.err.println("ACCESO MAL");
        }

//        try {
//            // TODO add your handling code here:
//            preconexion.actualizarPrimeraConexion("localhost",InetAddress.getLocalHost().getHostAddress(),"1234","ACTIVO");
//            System.err.println(""+InetAddress.getLocalHost().getHostAddress());
//        } catch (UnknownHostException ex) {
//            Logger.getLogger(ventanaServer.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }
    public void guardarIP() throws IOException {
        File archivo = new File("cnfg.ntw");

        //Crear objeto FileWriter que sera el que nos ayude a escribir sobre archivo
        BufferedWriter escribir = new BufferedWriter(new FileWriter(archivo));

        //Escribimos en el archivo con el metodo write 
        escribir.write("");
        escribir.write(InetAddress.getLocalHost().getHostAddress());

        //Cerramos la conexion
        escribir.close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
UIManager.setLookAndFeel(new WebLookAndFeel());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new ventanaServer().setVisible(estado);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JPasswordField campoPass;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
