/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.ManagerAsignarEquipo;
import Clases.ManagerUsers;
import Clases.ManagerSolicitud;
import Clases.ManagerPermisos;

import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kevin
 */
public class Ventana_EquipoComputo extends javax.swing.JDialog {
    ManagerAsignarEquipo manager_asignar;
    ManagerUsers manager_users;
    ManagerSolicitud manager_solicitud;
    ManagerPermisos manager_permisos;
    
    public static DefaultTableModel modeloAsignarEquipo;
    String[] Claves,Equipos;
    public static String Clave,tipo_solicitud;
    /**
     * Creates new form Ventana_asignar_EquipoComputo
     */
    public Ventana_EquipoComputo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Asignamos memoria al objeto
        manager_asignar = new ManagerAsignarEquipo();
        manager_users = new ManagerUsers();
        manager_solicitud = new ManagerSolicitud();
        manager_permisos = new ManagerPermisos();
        
        //Deshabilitamos el movimiento de los encabezados de las tablas
        tablaDetallesEquipos.getTableHeader().setReorderingAllowed(false);
        tablaEquipoComputo.getTableHeader().setReorderingAllowed(false);
        
        //Obtenemos el modelo de la tabla y luego se lo asingamos de nuevo
        /*Esto con la finalidad de agregar o quitar filas de dicha tabla*/
        modeloAsignarEquipo = (DefaultTableModel) this.tablaEquipoComputo.getModel();
        tablaEquipoComputo.setModel(modeloAsignarEquipo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuComputo = new javax.swing.JPopupMenu();
        SolicitarReemplazo = new javax.swing.JMenuItem();
        pn_asignarEquipo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetallesEquipos = new JTable(){  public boolean isCellEditable(int rowIndex, int colIndex){  return false;  }  };
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEquipoComputo = new JTable(){  public boolean isCellEditable(int rowIndex, int colIndex){  return false;  }  };

        SolicitarReemplazo.setText("Solicitar reemplazo");
        SolicitarReemplazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarReemplazoActionPerformed(evt);
            }
        });
        MenuComputo.add(SolicitarReemplazo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaDetallesEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "CPU", "Monitor", "Teclado", "Responsable"
            }
        ));
        tablaDetallesEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetallesEquiposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDetallesEquipos);

        tablaEquipoComputo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Equipo", "No. Serie", "Modelo"
            }
        ));
        tablaEquipoComputo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaEquipoComputoMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEquipoComputo);

        javax.swing.GroupLayout pn_asignarEquipoLayout = new javax.swing.GroupLayout(pn_asignarEquipo);
        pn_asignarEquipo.setLayout(pn_asignarEquipoLayout);
        pn_asignarEquipoLayout.setHorizontalGroup(
            pn_asignarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_asignarEquipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pn_asignarEquipoLayout.setVerticalGroup(
            pn_asignarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_asignarEquipoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pn_asignarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_asignarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_asignarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tablaDetallesEquipos.setModel(manager_asignar.getConjuntosEquipoComputo());
        
    }//GEN-LAST:event_formWindowOpened
    
    private void tablaDetallesEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetallesEquiposMouseClicked
        // TODO add your handling code here:

        if(evt.getClickCount() == 1){
            if(manager_permisos.consulta_asignacion(Principal.Username)){
                //Obtenemos la fila donde está el equipo de computo que queremos asignar
                int fila = tablaDetallesEquipos.getSelectedRow();

                //Obtenemos las claves de los equipos de computo de ese conjunto de equipos
                getDatosEquiposComputo(fila);
                tablaEquipoComputo.setModel(manager_asignar.getDetallesEquipoComputo(Claves));
            }else{
                JOptionPane.showMessageDialog(null, "Se te revocaron los permisos para consultar los conjuntos de los equipos de computo.");
            }
        }//getClickCount
    }//GEN-LAST:event_tablaDetallesEquiposMouseClicked
    public void getDatosEquiposComputo(int fila){
        Claves = new String[3];
        Equipos = new String[3];
        Claves[0] = tablaDetallesEquipos.getValueAt(fila, 1).toString();//Obtenemos la clave CPU
        Claves[1] = tablaDetallesEquipos.getValueAt(fila, 2).toString();//Obtenemos la clave Monitor
        Claves[2] = tablaDetallesEquipos.getValueAt(fila, 3).toString();//Obtenemos la clave Teclado
        
        //Equipos[i] = tablaEquipoComputo.getValueAt(i, 1).toString();//Obtenemos las claves
    }//getDatosTablaAsignarEquipo
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void tablaEquipoComputoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEquipoComputoMouseReleased
        // TODO add your handling code here:
        //Esto es para seleccionar con el click derecho y desplegar el menu solo cuando se seleccione una fila de la tabla
            if(SwingUtilities.isRightMouseButton(evt)){
                int r = tablaEquipoComputo.rowAtPoint(evt.getPoint());
                if (r >= 0 && r < tablaEquipoComputo.getRowCount())
                tablaEquipoComputo.setRowSelectionInterval(r, r);
                MenuComputo.show(evt.getComponent(), evt.getX(), evt.getY());//Mostramos el popMenu en la posición donde esta el cursor
            }//clic derecho
        
    }//GEN-LAST:event_tablaEquipoComputoMouseReleased

    private void SolicitarReemplazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarReemplazoActionPerformed
        // TODO add your handling code here:
        int fila = tablaEquipoComputo.getSelectedRow();
        tipo_solicitud = "Solicitud Reemplazo";
        Clave = tablaEquipoComputo.getValueAt(fila, 0).toString();
        //Buscamos el estado del producto que vamos a remover
        String estado = manager_solicitud.estadoProducto(Clave);
        
        if(estado.equals("ASIGNADO")){

            Principal.banderaSolicitud = 2;
            Ventana_solicitud ob = new Ventana_solicitud(this,true);
            ob.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "El equipo actualmente se encuentra en "+estado);
        }
    }//GEN-LAST:event_SolicitarReemplazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_EquipoComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_EquipoComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_EquipoComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_EquipoComputo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana_EquipoComputo dialog = new Ventana_EquipoComputo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu MenuComputo;
    private javax.swing.JMenuItem SolicitarReemplazo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pn_asignarEquipo;
    private javax.swing.JTable tablaDetallesEquipos;
    private javax.swing.JTable tablaEquipoComputo;
    // End of variables declaration//GEN-END:variables
}
